config_name = "Assemble with mips-linux-gnu-as"
preprocess = true
as_cmd = [
    "mips-linux-gnu-as {PREPROCESSED_AS} -o a.o",
    "mips-linux-gnu-objcopy -O binary --only-section=.text a.o {OUTPUT_AS}",
    "rm a.o"
]
